config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  get 'reports', to: 'reports#index'
  post 'reports', to: 'reports#index'

  resources :items
  resources :logs
end

app/models/log.rb
class Log < ApplicationRecord
  validates :item_title, presence: true, length: { minimum: 1, maximum: 100 }
  validates :item_sku, presence: true
  validates :item_brand, length: { maximum: 50 }
  validates :item_price, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates :item_quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :item_category, length: { maximum: 50 }
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: %i[show edit update destroy]

  # GET /logs or /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1 or /logs/1.json
  def show; end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit; end

  # POST /logs or /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to log_url(@log), notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1 or /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to log_url(@log), notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1 or /logs/1.json
  def destroy
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_log
    @log = Log.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def log_params
    params.require(:log).permit(:item_title, :item_sku, :item_price, :item_quantity, :item_brand, :item_category)
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_title %>
    <%= form.text_field :item_title %>
  </div>

  <div class="field">
    <%= form.label :item_sku %>
    <%= form.text_field :item_sku %>
  </div>

  <div class="field">
    <%= form.label :item_price %>
    <%= form.text_field :item_price %>
  </div>

  <div class="field">
    <%= form.label :item_quantity %>
    <%= form.number_field :item_quantity %>
  </div>

  <div class="field">
    <%= form.label :item_brand %>
    <%= form.text_field :item_brand %>
  </div>

  <div class="field">
    <%= form.label :item_category %>
    <%= form.text_field :item_category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th>Item title</th>
      <th>Item sku</th>
      <th>Item price</th>
      <th>Item quantity</th>
      <th>Item brand</th>
      <th>Item category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.item_title %></td>
        <td><%= log.item_sku %></td>
        <td><%= log.item_price %></td>
        <td><%= log.item_quantity %></td>
        <td><%= log.item_brand %></td>
        <td><%= log.item_category %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item title:</strong>
  <%= @log.item_title %>
</p>

<p>
  <strong>Item sku:</strong>
  <%= @log.item_sku %>
</p>

<p>
  <strong>Item price:</strong>
  <%= @log.item_price %>
</p>

<p>
  <strong>Item quantity:</strong>
  <%= @log.item_quantity %>
</p>

<p>
  <strong>Item brand:</strong>
  <%= @log.item_brand %>
</p>

<p>
  <strong>Item category:</strong>
  <%= @log.item_category %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>